name: "Build Artifact"

on:
  pull_request: {}
  # push: { branches: [master] }
  workflow_dispatch: {}

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_VERSION: 2020.3.11f1

jobs:
  build:
    name: ✨ Building for ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - WebGL # WebGL.

        include:
          - targetPlatform: StandaloneOSX
            name: 'OSX'
            channel: 'mac'

          - targetPlatform: StandaloneWindows64
            name: 'Windows'
            channel: 'windows'

          - targetPlatform: StandaloneLinux64
            name: 'Linux'
            channel: 'linux'

          - targetPlatform: WebGL
            name: 'WebGL'
            channel: 'webgl'

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - name: Caching
        uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
      
      # Create build path
      - name: Create the build path
        run: mkdir Build

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: ${{ matrix.targetPlatform }}
          buildsPath: Build

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.targetPlatform }}
          path: Build
